/*
 * Channel Access Token API
 *
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChannelAccessTokenKeyIdsResponse : Channel access token key IDs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelAccessTokenKeyIdsResponse {
    /// Array of channel access token key IDs.
    #[serde(rename = "kids")]
    pub kids: Vec<String>,
}

impl ChannelAccessTokenKeyIdsResponse {
    /// Channel access token key IDs
    pub fn new(kids: Vec<String>) -> ChannelAccessTokenKeyIdsResponse {
        ChannelAccessTokenKeyIdsResponse {
            kids,
        }
    }
}

