/*
 * Channel Access Token API
 *
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerifyChannelAccessTokenResponse : Verification result
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyChannelAccessTokenResponse {
    /// The channel ID for which the channel access token was issued.
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// Number of seconds before the channel access token expires.
    #[serde(rename = "expires_in")]
    pub expires_in: i64,
    /// Permissions granted to the channel access token.
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl VerifyChannelAccessTokenResponse {
    /// Verification result
    pub fn new(client_id: String, expires_in: i64) -> VerifyChannelAccessTokenResponse {
        VerifyChannelAccessTokenResponse {
            client_id,
            expires_in,
            scope: None,
        }
    }
}

