/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{FlexBubble, FlexCarousel};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FlexContainer {
    #[serde(rename = "bubble")]
    FlexBubble(FlexBubble),
    #[serde(rename = "carousel")]
    FlexCarousel(FlexCarousel),
}

impl Default for FlexContainer {
    fn default() -> Self {
        Self::FlexBubble(FlexBubble::default())
    }
}
