/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudienceGroupJobType : Job Type
/// Job Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AudienceGroupJobType {
    #[serde(rename = "DIFF_ADD")]
    DiffAdd,

}

impl std::fmt::Display for AudienceGroupJobType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DiffAdd => write!(f, "DIFF_ADD"),
        }
    }
}

impl Default for AudienceGroupJobType {
    fn default() -> AudienceGroupJobType {
        Self::DiffAdd
    }
}

