/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateImpBasedAudienceGroupResponse : Create audience for impression-based retargeting
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateImpBasedAudienceGroupResponse {
    /// The audience ID.
    #[serde(rename = "audienceGroupId", skip_serializing_if = "Option::is_none")]
    pub audience_group_id: Option<i64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::AudienceGroupType>,
    /// The audience's name.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// When the audience was created (in UNIX time).
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    /// The request ID that was specified when the audience was created.
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl CreateImpBasedAudienceGroupResponse {
    /// Create audience for impression-based retargeting
    pub fn new() -> CreateImpBasedAudienceGroupResponse {
        CreateImpBasedAudienceGroupResponse {
            audience_group_id: None,
            r#type: None,
            description: None,
            created: None,
            request_id: None,
        }
    }
}

