/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAudienceGroupAuthorityLevelResponse : Get the authority level of the audience
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAudienceGroupAuthorityLevelResponse {
    #[serde(rename = "authorityLevel", skip_serializing_if = "Option::is_none")]
    pub authority_level: Option<models::AudienceGroupAuthorityLevel>,
}

impl GetAudienceGroupAuthorityLevelResponse {
    /// Get the authority level of the audience
    pub fn new() -> GetAudienceGroupAuthorityLevelResponse {
        GetAudienceGroupAuthorityLevelResponse {
            authority_level: None,
        }
    }
}

