/*
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppTypeTile {
    /// users' OS
    #[serde(rename = "appType", skip_serializing_if = "Option::is_none")]
    pub app_type: Option<AppType>,
    /// Percentage
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
}

impl AppTypeTile {
    pub fn new() -> AppTypeTile {
        AppTypeTile {
            app_type: None,
            percentage: None,
        }
    }
}
/// users' OS
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AppType {
    #[serde(rename = "ios")]
    Ios,
    #[serde(rename = "android")]
    Android,
    #[serde(rename = "others")]
    Others,
}

impl Default for AppType {
    fn default() -> AppType {
        Self::Ios
    }
}

