/*
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetStatisticsPerUnitResponseOverview : Statistics related to messages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatisticsPerUnitResponseOverview {
    /// Number of users who opened the message, meaning they displayed at least 1 bubble.
    #[serde(rename = "uniqueImpression", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unique_impression: Option<Option<i64>>,
    /// Number of users who opened any URL in the message.
    #[serde(rename = "uniqueClick", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unique_click: Option<Option<i64>>,
    /// Number of users who started playing any video or audio in the message.
    #[serde(rename = "uniqueMediaPlayed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unique_media_played: Option<Option<i64>>,
    /// Number of users who played the entirety of any video or audio in the message.
    #[serde(rename = "uniqueMediaPlayed100Percent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unique_media_played100_percent: Option<Option<i64>>,
}

impl GetStatisticsPerUnitResponseOverview {
    /// Statistics related to messages.
    pub fn new() -> GetStatisticsPerUnitResponseOverview {
        GetStatisticsPerUnitResponseOverview {
            unique_impression: None,
            unique_click: None,
            unique_media_played: None,
            unique_media_played100_percent: None,
        }
    }
}

