/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{AttachedModuleContent, DetachedModuleContent};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ModuleContent {
    #[serde(rename = "attached")]
    AttachedModuleContent(AttachedModuleContent),
    #[serde(rename = "detached")]
    DetachedModuleContent(DetachedModuleContent),
}

impl Default for ModuleContent {
    fn default() -> Self {
        Self::AttachedModuleContent(AttachedModuleContent::default())
    }
}
