/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateImpBasedAudienceGroupRequest : Create audience for impression-based retargeting
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateImpBasedAudienceGroupRequest {
    /// The audience's name. This is case-insensitive, meaning `AUDIENCE` and `audience` are considered identical. Max character limit: 120 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The request ID of a broadcast or narrowcast message sent in the past 60 days. Each Messaging API request has a request ID. 
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl CreateImpBasedAudienceGroupRequest {
    /// Create audience for impression-based retargeting
    pub fn new() -> CreateImpBasedAudienceGroupRequest {
        CreateImpBasedAudienceGroupRequest {
            description: None,
            request_id: None,
        }
    }
}

