/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserMentionTarget {
    /// Target to be mentioned
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl UserMentionTarget {
    pub fn new(r#type: String, user_id: String) -> UserMentionTarget {
        UserMentionTarget {
            r#type: Some(r#type),
            user_id,
        }
    }
}
