/*
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllLiffAppsResponse {
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<Vec<models::LiffApp>>,
}

impl GetAllLiffAppsResponse {
    pub fn new() -> GetAllLiffAppsResponse {
        GetAllLiffAppsResponse {
            apps: None,
        }
    }
}

