/*
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddLiffAppResponse {
    #[serde(rename = "liffId")]
    pub liff_id: String,
}

impl AddLiffAppResponse {
    pub fn new(liff_id: String) -> AddLiffAppResponse {
        AddLiffAppResponse {
            liff_id,
        }
    }
}

