/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{AllMentionee, UserMentionee};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Mentionee {
    #[serde(rename = "all")]
    AllMentionee(AllMentionee),
    #[serde(rename = "user")]
    UserMentionee(UserMentionee),
}

impl Default for Mentionee {
    fn default() -> Self {
        Self::AllMentionee(AllMentionee::default())
    }
}
